# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-21 23:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Door',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('door_name', models.CharField(max_length=144)),
                ('door_type', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(max_length=20)),
                ('open_level', models.IntegerField(default=0)),
                ('time_stamp', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('door', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doorlogger.Door')),
            ],
        ),
    ]
