# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-31 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doorlogger', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='time_stamp',
            field=models.DateTimeField(verbose_name='time stamp'),
        ),
    ]
